version: '3'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  cue:
    build:
      context: py_scripts
      dockerfile: Dockerfile
    depends_on:
      - server
    stdin_open: true  # docker run -i
    tty: true         # docker run -t