[package]
name = "txt2post"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.14"
serde = "1.0.152"
termion = "2.0.1"
tokio = {version ="1.25.0", features=["full"]}
